# Generated by Django 5.1.5 on 2025-02-04 09:35

import airline.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Airplane",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tail_number", models.CharField(max_length=50, unique=True)),
                ("model", models.TextField()),
                ("capacity", models.IntegerField()),
                (
                    "production_year",
                    models.IntegerField(validators=[airline.models.validate_year]),
                ),
                ("status", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="Flight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("flight_number", models.TextField()),
                ("departure", models.TextField()),
                ("destination", models.TextField()),
                ("departure_time", models.DateTimeField()),
                ("arrival_time", models.DateTimeField()),
                (
                    "airplane",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flights",
                        to="airline.airplane",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("passenger_name", models.TextField()),
                ("passenger_email", models.TextField()),
                (
                    "reservation_code",
                    models.CharField(default=uuid.uuid4, max_length=50, unique=True),
                ),
                ("status", models.BooleanField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "flight",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to="airline.flight",
                    ),
                ),
            ],
        ),
    ]
