# Generated by Django 5.1.5 on 2025-02-04 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='passenger_email',
            field=models.EmailField(max_length=254),
        ),
    ]
