# Generated by Django 5.1.5 on 2025-02-07 05:36

import airline.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airline", "0002_alter_reservation_passenger_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="airplane",
            name="capacity",
            field=models.IntegerField(validators=[airline.models.validate_capacity]),
        ),
        migrations.AlterField(
            model_name="flight",
            name="flight_number",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="reservation_code",
            field=models.CharField(
                default=airline.models.generate_reservation_code,
                max_length=50,
                unique=True,
            ),
        ),
    ]
