# Generated by Django 5.1.5 on 2025-02-07 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airline", "0003_alter_airplane_capacity_alter_flight_flight_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="flight",
            name="reservation_count",
            field=models.IntegerField(default=0),
        ),
    ]
